#!/usr/bin/env bash

readonly swiftFormat="$(which swift-format)"
if [[ -z "${swiftFormat}" || ! -x "${swiftFormat}" ]]; then
  echo "Tool swift-format is not found. Please install swift-format via brew or visit https://github.com/apple/swift-format" > /dev/stderr
  exit 1
fi

function runSwiftFormat() {
  "${swiftFormat}" \
    --recursive \
    --parallel \
    --in-place \
    --ignore-unparsable-files \
    "${1}"
}


find Sources Tests "${PWD}" \
    -maxdepth 1 \
    -type f \
    -name '*.swift' \
    -exec \
        "${swiftFormat}" \
          --recursive \
          --parallel \
          --in-place \
          --ignore-unparsable-files \
          {} \;
